# Generated by Django 5.0.2 on 2024-11-17 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='اسم العقار')),
                ('description', models.TextField(verbose_name='وصف العقار')),
                ('price_per_month', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='السعر لكل شهر')),
                ('location', models.CharField(max_length=255, verbose_name='الموقع')),
                ('available', models.DateField(default=True, verbose_name='متاح للايجار')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
            ],
        ),
    ]
