# Generated by Django 5.0.3 on 2024-11-19 18:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0004_property_category'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PropertyFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='الميزة')),
                ('description', models.TextField(blank=True, verbose_name='وصف الميزة')),
            ],
            options={
                'verbose_name': 'ميزة العقار',
                'verbose_name_plural': 'ميزات العقارات',
            },
        ),
        migrations.RemoveField(
            model_name='property',
            name='available',
        ),
        migrations.AddField(
            model_name='property',
            name='area',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10, verbose_name='المساحة بالمتر المربع'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='property',
            name='bathrooms',
            field=models.PositiveIntegerField(default=1, verbose_name='عدد الحمامات'),
        ),
        migrations.AddField(
            model_name='property',
            name='latitude',
            field=models.DecimalField(decimal_places=6, default=1, max_digits=10, verbose_name='خط العرض'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='property',
            name='longitude',
            field=models.DecimalField(decimal_places=6, default=1, max_digits=10, verbose_name='خط الطول'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='property',
            name='rooms',
            field=models.PositiveIntegerField(default=1, verbose_name='عدد الغرف'),
        ),
        migrations.AddField(
            model_name='property',
            name='status',
            field=models.CharField(choices=[('Available', 'متوفر'), ('Rented', 'مؤجر'), ('Unavailable', 'غير متاح')], default='Available', max_length=15, verbose_name='الحالة'),
        ),
        migrations.AlterField(
            model_name='property',
            name='description',
            field=models.TextField(verbose_name='الوصف'),
        ),
        migrations.AlterField(
            model_name='property',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='properties', to=settings.AUTH_USER_MODEL, verbose_name='المالك'),
        ),
    ]
