# Generated by Django 5.0.3 on 2024-11-19 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0004_booking_comments'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='comments',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='is_approved',
        ),
        migrations.AddField(
            model_name='booking',
            name='cancellation_date',
            field=models.DateField(blank=True, null=True, verbose_name='تاريخ الإلغاء'),
        ),
        migrations.AddField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('Pending', 'في الانتظار'), ('Confirmed', 'مقبول'), ('Cancelled', 'ملغى')], default='Pending', max_length=15, verbose_name='حالة الحجز'),
        ),
        migrations.AddField(
            model_name='review',
            name='verified',
            field=models.BooleanField(default=False, verbose_name='تم التحقق'),
        ),
    ]
